<?php

namespace Database\Seeders;

use App\Models\Challenge;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChallengeSeeder extends Seeder
{
    public function run(): void
    {
        $challenges = [
            [
                'title' => 'Sétaindító',
                'description' => 'Teljesíts ma legalább 20 perc walking aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'cardio',
                'activity_type' => 'walking',
                'target_value' => 20,
            ],
            [
                'title' => 'Sétamester',
                'description' => 'Teljesíts ma legalább 40 perc walking aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'cardio',
                'activity_type' => 'walking',
                'target_value' => 40,
            ],
            [
                'title' => 'Futóstart',
                'description' => 'Teljesíts ma legalább 15 perc running aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'cardio',
                'activity_type' => 'running',
                'target_value' => 15,
            ],
            [
                'title' => 'Futólendület',
                'description' => 'Teljesíts ma legalább 25 perc running aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'cardio',
                'activity_type' => 'running',
                'target_value' => 25,
            ],
            [
                'title' => 'Biciklis kör',
                'description' => 'Teljesíts ma legalább 20 perc cycling aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'cardio',
                'activity_type' => 'cycling',
                'target_value' => 20,
            ],
            [
                'title' => 'Hosszabb tekerés',
                'description' => 'Teljesíts ma legalább 35 perc cycling aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'cardio',
                'activity_type' => 'cycling',
                'target_value' => 35,
            ],
            [
                'title' => 'Ússz bele',
                'description' => 'Teljesíts ma legalább 15 perc swimming aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'cardio',
                'activity_type' => 'swimming',
                'target_value' => 15,
            ],
            [
                'title' => 'Erős kezdés',
                'description' => 'Teljesíts ma legalább 20 perc weightlifting aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'strength',
                'activity_type' => 'weightlifting',
                'target_value' => 20,
            ],
            [
                'title' => 'Súlyzós nap',
                'description' => 'Teljesíts ma legalább 35 perc weightlifting aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'strength',
                'activity_type' => 'weightlifting',
                'target_value' => 35,
            ],
            [
                'title' => 'Saját testsúlyos blokk',
                'description' => 'Teljesíts ma legalább 20 perc bodyweight aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'strength',
                'activity_type' => 'bodyweight',
                'target_value' => 20,
            ],
            [
                'title' => 'Bodyweight plusz',
                'description' => 'Teljesíts ma legalább 30 perc bodyweight aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'strength',
                'activity_type' => 'bodyweight',
                'target_value' => 30,
            ],
            [
                'title' => 'Meditációs szünet',
                'description' => 'Teljesíts ma legalább 10 perc meditation aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'mental',
                'activity_type' => 'meditation',
                'target_value' => 10,
            ],
            [
                'title' => 'Mély fókusz',
                'description' => 'Teljesíts ma legalább 20 perc meditation aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'mental',
                'activity_type' => 'meditation',
                'target_value' => 20,
            ],
            [
                'title' => 'Jóga percek',
                'description' => 'Teljesíts ma legalább 15 perc yoga aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'mental',
                'activity_type' => 'yoga',
                'target_value' => 15,
            ],
            [
                'title' => 'Nyugodt áramlás',
                'description' => 'Teljesíts ma legalább 25 perc yoga aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'mental',
                'activity_type' => 'yoga',
                'target_value' => 25,
            ],
            [
                'title' => 'Olvasási blokk',
                'description' => 'Teljesíts ma legalább 20 perc reading aktivitást.',
                'challenge_type' => 'activity_duration',
                'category' => 'mental',
                'activity_type' => 'reading',
                'target_value' => 20,
            ],
            [
                'title' => 'Cardio pontvadász',
                'description' => 'Gyűjts ma legalább 40 cardio pontot.',
                'challenge_type' => 'activity_points',
                'category' => 'cardio',
                'activity_type' => null,
                'target_value' => 40,
            ],
            [
                'title' => 'Cardio haladó',
                'description' => 'Gyűjts ma legalább 70 cardio pontot.',
                'challenge_type' => 'activity_points',
                'category' => 'cardio',
                'activity_type' => null,
                'target_value' => 70,
            ],
            [
                'title' => 'Erőpont gyűjtés',
                'description' => 'Gyűjts ma legalább 35 strength pontot.',
                'challenge_type' => 'activity_points',
                'category' => 'strength',
                'activity_type' => null,
                'target_value' => 35,
            ],
            [
                'title' => 'Erőfókusz',
                'description' => 'Gyűjts ma legalább 60 strength pontot.',
                'challenge_type' => 'activity_points',
                'category' => 'strength',
                'activity_type' => null,
                'target_value' => 60,
            ],
            [
                'title' => 'Mentális egyensúly',
                'description' => 'Gyűjts ma legalább 20 mental pontot.',
                'challenge_type' => 'activity_points',
                'category' => 'mental',
                'activity_type' => null,
                'target_value' => 20,
            ],
            [
                'title' => 'Mentális extra',
                'description' => 'Gyűjts ma legalább 35 mental pontot.',
                'challenge_type' => 'activity_points',
                'category' => 'mental',
                'activity_type' => null,
                'target_value' => 35,
            ],
            [
                'title' => 'Mozgásban a nap',
                'description' => 'Gyűjts ma legalább 80 összes aktivitáspontot.',
                'challenge_type' => 'activity_points_total',
                'category' => null,
                'activity_type' => null,
                'target_value' => 80,
            ],
            [
                'title' => 'Nagy aktivitásnap',
                'description' => 'Gyűjts ma legalább 120 összes aktivitáspontot.',
                'challenge_type' => 'activity_points_total',
                'category' => null,
                'activity_type' => null,
                'target_value' => 120,
            ],
            [
                'title' => 'Fehérjestart',
                'description' => 'Fogyassz ma legalább 60 g fehérjét.',
                'challenge_type' => 'protein_min',
                'category' => null,
                'activity_type' => null,
                'target_value' => 60,
            ],
            [
                'title' => 'Fehérjebomba',
                'description' => 'Fogyassz ma legalább 90 g fehérjét.',
                'challenge_type' => 'protein_min',
                'category' => null,
                'activity_type' => null,
                'target_value' => 90,
            ],
            [
                'title' => 'Magas fehérjenap',
                'description' => 'Fogyassz ma legalább 120 g fehérjét.',
                'challenge_type' => 'protein_min',
                'category' => null,
                'activity_type' => null,
                'target_value' => 120,
            ],
            [
                'title' => 'Naplózd a napod',
                'description' => 'Rögzíts ma legalább 2 fogyasztási bejegyzést.',
                'challenge_type' => 'food_log_count',
                'category' => null,
                'activity_type' => null,
                'target_value' => 2,
            ],
            [
                'title' => 'Étkezési fegyelem',
                'description' => 'Rögzíts ma legalább 3 fogyasztási bejegyzést.',
                'challenge_type' => 'food_log_count',
                'category' => null,
                'activity_type' => null,
                'target_value' => 3,
            ],
            [
                'title' => 'Teljes naplózás',
                'description' => 'Rögzíts ma legalább 4 fogyasztási bejegyzést.',
                'challenge_type' => 'food_log_count',
                'category' => null,
                'activity_type' => null,
                'target_value' => 4,
            ],
        ];

        foreach ($challenges as $challenge) {
            Challenge::create([
                ...$challenge,
                'reward_xp' => 50,
                'is_active' => true,
            ]);
        }
    }
}
